### ISSUE TITLE
[Question] Future of crunchyroll and download

### ISSUE THREAD

**Issue by N3ars** [Tenpi/Crunchyroll-Downloader#18]
I saw a comment from #17 about beta so was curious so i did inspect network monoitor of the page, i saw that there is now a license url which is from the widevine drm (maybe it did already exist since long time idk), my question is this gonna be like that for every video and can we still download in the future with maybe a bypass or we gonna get slammed in the face? thanks.

**Comment by Tenpi** [comment]
Yes, if they switch to DRM-encrypted streams like Netflix/Hulu it won't be possible to download from them anymore. I'm not interested in decrypting DRM since it's illegal. Unfortunately, it might be what they plan to do when the beta replaces the regular site, since I don't recall them being there before, but for now they are still using the DRM-free streams.

**Comment by N3ars** [comment]
I see thanks for clarification!
