### ISSUE TITLE
New version for linux

### ISSUE THREAD

**Issue by lucaslira95** [Tenpi/Crunchyroll-Downloader#38]
Would be good to have a linux version of this software.
I already tried to compile source myself but there is packages imcompatible with linux.
For personal motives, I cannot try with wine, and I think linux users would like a linux version too...

**Comment by Tenpi** [comment]
Sorry, I forgot to push the changes that I made to make it compile on macOS. Now it should compile on any OS since the Windows-only dependency is optional.

You are welcome to compile source yourself, make the required changes to make it work on Linux, and then submit a pull request. I am currently using an M1 Pro MBP and installing Linux on it might be a pain. 

In short:
- Add a linux ffmpeg executable to the ffmpeg folder
- Add the new `ffmpegPath` to the file `main.ts`
- Add a linux target for [electron-builder](https://www.electron.build) in `package.json`

**Comment by Tenpi** [comment]
The Linux version was added in `v0.3.6`.
