### ISSUE TITLE
Output language in the name of the episode.

### ISSUE THREAD

**Issue by SpainEs** [Tenpi/Crunchyroll-Downloader#49]
First, Thanks for your work!

Could it be possible to change the configuration to output the name of the episode in the same subs language chosen? It always in English. I'm Spanish and I would like it to come out like this:

Default:
Naruto/Naruto Season 1/1-Enter Naruto Uzumaki!.mp4
What I would like:
Naruto/Temporada 1/1 – ¡Naruto Uzumaki ya está aquí!.mp4

**Comment by Tenpi** [comment]
I think I forced it to use the english site because of some bugs, but I have removed the locale strip and it still seems to work.

You MUST either pass in the URL to the spanish site, or change the language of the CR site in the browser to "spanish" eg.
https://www.crunchyroll.com/es-es/naruto/episode-1-enter-naruto-uzumaki-519936
instead of
https://www.crunchyroll.com/naruto/episode-1-enter-naruto-uzumaki-519936

I think the latter URL uses your location to get the language, so if you are in the US it will probably always return the english site.
