### ISSUE TITLE
Got orange window

### ISSUE THREAD

**Issue by N3ars** [Tenpi/Crunchyroll-Downloader#8]
Hi there
Thanks for this great app!
I have a problem tho, I got an orange window screen when i press the search button, when i put the whole anime for example [https://www.crunchyroll.com/fr/burn-the-witch](https://www.crunchyroll.com/fr/burn-the-witch) , i guess it's downloading as i can see in the task manager but i can't see what's going on

![d4Cr6wn](https://user-images.githubusercontent.com/41067116/111166226-2f508600-85a0-11eb-82e7-d350883d4e11.png)
![F6F3wiv](https://user-images.githubusercontent.com/41067116/111166229-2fe91c80-85a0-11eb-9a46-0025dc9c772b.png)

**Comment by Tenpi** [comment]
Orange window means that it crashed, in this case your link is not supported because it is https://www.crunchyroll.com/fr/ and not https://www.crunchyroll.com/.

To fix it, you can use the link https://www.crunchyroll.com/burn-the-witch. But in the next update I will automatically strip out the locale.

**Comment by N3ars** [comment]
Hmmm I just tried [https://www.crunchyroll.com/burn-the-witch](https://www.crunchyroll.com/burn-the-witch) doesn't seem to work either, still have orange window, the thing is it's downloading and even finished, the only issue here is not able to see the progress, not a big deal tho, i don't have that in single download episode with the same /fr/ link only when i try multi download.

**Comment by Tenpi** [comment]
Didn't mean to close that, let me know if the update fixed it for you (`v0.1.8`).

**Comment by N3ars** [comment]
Unfortunately, the new version didn't fix the problem. Maybe is on my side? Do you also have this issue or it's only me

**Comment by Tenpi** [comment]
Ok, so if you're in France then using the base crunchyroll link might redirect to the French site, which is why it works for me and not for you. I need to force the English site, so I actually change all the links to https://www.crunchyroll.com/en-gb/ instead. Let me know if that fixes the problem by updating to `v0.1.9`.

**Comment by N3ars** [comment]
Yes! It's working fine now, thank you for your help!
